baseURL = 'https://0a6419a5.drift-journal.pages.dev/'

languageCode = 'en-us'
title = 'Drift: a journal of roamings in the margins of archaeology'
theme = 'ananke'
resourceDir = "../resources"
#canonifyURLs = true
# relativeURLs = true
copyright = "Drift is an open access journal. ISSN 1363-5387. DOI: 10.11141/issn.1363-5387. Email: drift at drift.org."

publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"


[params]
text_color = ""
author = ""
favicon = ""
# site_logo = "img/logo.png"
description = "_Drift: a journal of roamings in the margins of archaeology_ is independent, free,  global and open journal that encourages free exploration of ideas, permitting writing in a conversational, introspective style that doesn’t easily fit elsewhere."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3


[params.ananke.social.follow]
networks = [
  "bluesky"

]

[params.ananke.social.bluesky]
username = "dimitrij"

